services:
  db:
    image: postgres:15
    container_name: hotel_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hotel_db
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d hotel_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: hotel_app
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: password
      DB_NAME: hotel_db
      JWT_SECRET: supersecretkey
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
